### ISSUE TITLE
Cannot access offset of type string on string

### ISSUE THREAD

**Issue by pajkho** [huzaifaarain/telescope-guzzle-watcher#13]
Line 189 in TelescopeGuzzleRecorder.php (if ($data['contents'] instanceof File) {) is throwing the below error for us in some instances.

Cannot access offset of type string on string

@huzaifaarain do we need to add a check to see if $data['contents'] isset? Or any other ideas how to best fix this?

**Comment by huzaifaarain** [comment]
Hi @pajkho 

thanks for identifying the issue i'll look into it later today, seems like an issue with multipart requests.

**Comment by pajkho** [comment]
> Hi @pajkho 
> 
> thanks for identifying the issue i'll look into it later today, seems like an issue with multipart requests.

Thanks, much appreciated!

**Comment by pajkho** [comment]
> Hi @pajkho 
> 
> thanks for identifying the issue i'll look into it later today, seems like an issue with multipart requests.

Hi @huzaifaarain !

Just wanted to check if you've had a chance to check this yet? Any solution coming soon? 😊

I totally understand if you have other priorities. Just wanted to check the status.

**Comment by pajkho** [comment]
Hi @huzaifaarain 

What do you think about wrapping the whole recordRequest() with a try catch? This way if anything fails it wont affect the rest of the application. I think most cases in production its much better with the recorder silently failing rather than having the whole request fail.

I can make a PR for this if you want, or if you prefer to do it yourself.

**Comment by huzaifaarain** [comment]
Hi @pajkho 

I wasn't comfortable with just try catch, the package had no support for multipart requests but now it does, install the latest version and let me know if you face any issue.

Regards
