### ISSUE TITLE
Add support for Laravel 11

### ISSUE THREAD

**Issue by G4Zz0L1** [huzaifaarain/telescope-guzzle-watcher#3]
Laravel 11 is out, can you add support for it?
Thanks in advance!

**Comment by huzaifaarain** [comment]
Sure @G4Zz0L1 , Its in progress.

**Comment by G4Zz0L1** [comment]
Ok, I've seen the PR https://github.com/huzaifaarain/telescope-guzzle-watcher/pull/6 now, I'll wait for it to merge.
Thanks!

**Comment by G4Zz0L1** [comment]
Any news on this?
Otherwise, I'll be forced to remove the package in order to upgrade, until Laravel 11 is properly supported.
Thanks in advance!

**Comment by huzaifaarain** [comment]
@G4Zz0L1 I'll do it later today, was on bed rest due to sickness.

Thanks

**Comment by G4Zz0L1** [comment]
@huzaifaarain I hope you're feeling better soon!
Health comes first, so please take your time and prioritize your recovery.
We appreciate your efforts and understand that unforeseen circumstances can arise.
Looking forward to the update when you're ready.
Take care!

**Comment by huzaifaarain** [comment]
@G4Zz0L1 Laravel 11 support has been added. v3 now supports laravel 11

Merged https://github.com/huzaifaarain/telescope-guzzle-watcher/pull/6
